'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Transparent")>  _
        Public Property ForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100, 100")>  _
        Public Property clLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("clLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("clLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Harry P, 17.9999981pt")>  _
        Public Property Harry_PotterF() As Global.System.Drawing.Font
            Get
                Return CType(Me("Harry_PotterF"),Global.System.Drawing.Font)
            End Get
            Set
                Me("Harry_PotterF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Info")>  _
        Public Property Harry_PotterC() As Global.System.Drawing.Color
            Get
                Return CType(Me("Harry_PotterC"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Harry_PotterC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 192, 0")>  _
        Public Property MatrixC() As Global.System.Drawing.Color
            Get
                Return CType(Me("MatrixC"),Global.System.Drawing.Color)
            End Get
            Set
                Me("MatrixC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("BackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("BackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Transparent() As Boolean
            Get
                Return CType(Me("Transparent"),Boolean)
            End Get
            Set
                Me("Transparent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Tick() As Boolean
            Get
                Return CType(Me("Tick"),Boolean)
            End Get
            Set
                Me("Tick") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Background() As String
            Get
                Return CType(Me("Background"),String)
            End Get
            Set
                Me("Background") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BackgroundBool() As Boolean
            Get
                Return CType(Me("BackgroundBool"),Boolean)
            End Get
            Set
                Me("BackgroundBool") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BackColorBool() As Boolean
            Get
                Return CType(Me("BackColorBool"),Boolean)
            End Get
            Set
                Me("BackColorBool") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AlertDay() As Boolean
            Get
                Return CType(Me("AlertDay"),Boolean)
            End Get
            Set
                Me("AlertDay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AlertHour() As Boolean
            Get
                Return CType(Me("AlertHour"),Boolean)
            End Get
            Set
                Me("AlertHour") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowTop() As Boolean
            Get
                Return CType(Me("ShowTop"),Boolean)
            End Get
            Set
                Me("ShowTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property calendarLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("calendarLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("calendarLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property calendarSToday() As Boolean
            Get
                Return CType(Me("calendarSToday"),Boolean)
            End Get
            Set
                Me("calendarSToday") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property calendarCircle() As Boolean
            Get
                Return CType(Me("calendarCircle"),Boolean)
            End Get
            Set
                Me("calendarCircle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property calendarWeek() As Boolean
            Get
                Return CType(Me("calendarWeek"),Boolean)
            End Get
            Set
                Me("calendarWeek") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1, 1")>  _
        Public Property calendarDS() As Global.System.Drawing.Size
            Get
                Return CType(Me("calendarDS"),Global.System.Drawing.Size)
            End Get
            Set
                Me("calendarDS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Default")>  _
        Public Property calendarFdayW() As Global.System.Windows.Forms.Day
            Get
                Return CType(Me("calendarFdayW"),Global.System.Windows.Forms.Day)
            End Get
            Set
                Me("calendarFdayW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property calendarMaxSel() As Integer
            Get
                Return CType(Me("calendarMaxSel"),Integer)
            End Get
            Set
                Me("calendarMaxSel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LongTime")>  _
        Public Property Time_Format() As Global.Microsoft.VisualBasic.DateFormat
            Get
                Return CType(Me("Time_Format"),Global.Microsoft.VisualBasic.DateFormat)
            End Get
            Set
                Me("Time_Format") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LongDate")>  _
        Public Property Date_Format() As Global.Microsoft.VisualBasic.DateFormat
            Get
                Return CType(Me("Date_Format"),Global.Microsoft.VisualBasic.DateFormat)
            End Get
            Set
                Me("Date_Format") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2012-03-12")>  _
        Public Property AlarmTime() As Date
            Get
                Return CType(Me("AlarmTime"),Date)
            End Get
            Set
                Me("AlarmTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AlarmPath() As String
            Get
                Return CType(Me("AlarmPath"),String)
            End Get
            Set
                Me("AlarmPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Alarm() As Boolean
            Get
                Return CType(Me("Alarm"),Boolean)
            End Get
            Set
                Me("Alarm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AlarmCustom() As Boolean
            Get
                Return CType(Me("AlarmCustom"),Boolean)
            End Get
            Set
                Me("AlarmCustom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AlarmTone() As Boolean
            Get
                Return CType(Me("AlarmTone"),Boolean)
            End Get
            Set
                Me("AlarmTone") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AlarmText() As Boolean
            Get
                Return CType(Me("AlarmText"),Boolean)
            End Get
            Set
                Me("AlarmText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Shakir. Wake up.")>  _
        Public Property AlarmPathText() As String
            Get
                Return CType(Me("AlarmPathText"),String)
            End Get
            Set
                Me("AlarmPathText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property AlarmTheme() As Integer
            Get
                Return CType(Me("AlarmTheme"),Integer)
            End Get
            Set
                Me("AlarmTheme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AlarmImage() As String
            Get
                Return CType(Me("AlarmImage"),String)
            End Get
            Set
                Me("AlarmImage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property AlarmColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("AlarmColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("AlarmColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AlarmAlertText() As String
            Get
                Return CType(Me("AlarmAlertText"),String)
            End Get
            Set
                Me("AlarmAlertText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AlarmIsColor() As Boolean
            Get
                Return CType(Me("AlarmIsColor"),Boolean)
            End Get
            Set
                Me("AlarmIsColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 15.75pt")>  _
        Public Property Font() As Global.System.Drawing.Font
            Get
                Return CType(Me("Font"),Global.System.Drawing.Font)
            End Get
            Set
                Me("Font") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Matrix, 14.25pt")>  _
        Public Property MatrixF() As Global.System.Drawing.Font
            Get
                Return CType(Me("MatrixF"),Global.System.Drawing.Font)
            End Get
            Set
                Me("MatrixF") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Neutrino_Digital_Clock.My.MySettings
            Get
                Return Global.Neutrino_Digital_Clock.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
